library(rpart)
library(AppliedPredictiveModeling)
data(concrete)
1.
set.seed(1)
train<-sample(1030,730)
set.seed(123)
fit<-rpart(CompressiveStrength~.,data=concrete,subset=train)
plot(fit)
2.
op<-par(no.readonly=TRUE)
par(mar=c(1,1,1,1))
plot(fit,margin=0.1)
text(fit)
par(op)
3.
plotcp(fit)
fit$cptable
min_cp<-fit$cptable[which.min(fit$cptable[,"xerror"]),"CP"]
min_cp
4.
fit_best<-prune(fit,cp=min_cp)
library(rpart.plot)
prp(fit_best,type=2)
5.
tree.pred<-predict(fit_best,newdata=concrete[-train,])
y.test<-concrete[-train,"CompressiveStrength"]
mean((tree.pred-y.test)^2)

6.
ols.fit<-lm(CompressiveStrength~.,concrete,subset=train)
ols.pred<-predict(ols.fit,newdata=concrete[-train,])
mean((ols.pred-y.test)^2)
plot(ols.pred,y.test,main="ols")
abline(0,1)

